### PR TITLE
adding plots to cleaned.ipynb

### PR DESCRIPTION
**Pull request by monicafar147**

### CODE REVIEW

**Comment by monicafar147** [comment]
prediction_plot

**Comment by monicafar147** [comment]
@fossilgenera are these plots ok? do you want them in different colours? labels? indivdual
the plots are saved as a.png file that I can send to you for the slides

**Comment by monicafar147** [comment]
rmse_plot (2)

**Comment by fossilgenera** [comment]
Could you change "Best random forest" to "Random search random forest" or something, to indicate that we used the random search method for the tuning. Otherwise, those are great.

Additionally, could you please change the RSME graph to a bar graph instead of scatter plot?

**Comment by monicafar147** [comment]
made better plots

**Comment by monicafar147** [comment]
rmse_plot_part1

**Comment by monicafar147** [comment]
rmse_plot_part2

**Pull request closed without merging**
