### PR TITLE
added data preprocessing only

### PR DESCRIPTION
**Pull request by fossilgenera**

### CODE REVIEW

**Comment by monicafar147** [comment]
image
 I propose the following naming convention?

**Comment by fossilgenera** [comment]
I think we can remove the "Mo=1" part from the weekday columns

**Comment by monicafar147** [comment]
ok cool will do

**Comment by monicafar147** [comment]
image

Removed the "Mo=1" we can even use underscores? But at the moment it looks very neat

**Comment by fossilgenera** [comment]
I think this looks good.

**Comment by monicafar147** [comment]
Ok just going to change all the column names to this convention then Ill commit and then you can merge

**Comment by monicafar147** [comment]
I am getting this error 
image

**Comment by fossilgenera** [comment]
I've fixed the error. I added in an extra parameter to the assign_time_category function but didn't end up using it and forgot to remove it.

**Comment by monicafar147** [comment]
Ok you can merge, everything runs. Next we need to add the models

**Pull request merged**
